-- Begin the transaction
BEGIN;

-- Truncate all tables to remove all data

TRUNCATE TABLE LibraryEmployee RESTART IDENTITY CASCADE;
TRUNCATE TABLE StoreOperator RESTART IDENTITY CASCADE;
TRUNCATE TABLE Librarian RESTART IDENTITY CASCADE;
TRUNCATE TABLE Security RESTART IDENTITY CASCADE;
TRUNCATE TABLE DeskPersonnel RESTART IDENTITY CASCADE;
TRUNCATE TABLE Marketer RESTART IDENTITY CASCADE;
TRUNCATE TABLE SocialMedia RESTART IDENTITY CASCADE;
TRUNCATE TABLE Manages RESTART IDENTITY CASCADE;

-- Commit the transaction
COMMIT;
